### ISSUE TITLE
Running the build?

### ISSUE THREAD

**Issue by niccolomineo** [tfnico/vim-gradle#4]
After `:compiler gradle`ing and `:make build`ing a .gradle file containing Groovy code, this is what I get and I don't know how to run the build:
![schermata 2016-01-07 alle 21 02 31](https://cloud.githubusercontent.com/assets/5409469/12181441/7ec8c7b8-b582-11e5-9d93-e945965e3946.png)

Thank you for shedding light, I am new to using ViM to compile/run

**Comment by tfnico** [comment]
I have no idea about this, as I don't use the :compiler gradle stuff myself. Any idea, @nathanalderson?

Looks to me like the build was successful anyhow..

**Comment by nathanalderson** [comment]
Agreed: it looks like it worked.  What happens when you run `:!gradle build`? What happens when you run `gradle build` from the command line? Maybe make sure vim is in the right working directory (`:pwd`)?

**Comment by niccolomineo** [comment]
Thanks for replying.

:!gradle build results in this:
![schermata 2016-01-08 alle 17 26 47](https://cloud.githubusercontent.com/assets/5409469/12203018/0c0f3d50-b62d-11e5-87ff-b74369492d9b.png)

:pwd results in this (the correct project path:
![schermata 2016-01-08 alle 17 23 21](https://cloud.githubusercontent.com/assets/5409469/12202928/9d8b2d12-b62c-11e5-9f9b-8d62a836601f.png)

The groovy code I am trying to build is the following:

´´´
    String str
    print "Please key in a word: "
    str = System.console().readList()
    println "The word was: " + attr
    print "Now please key in another: "
    str = System.console().readLine()
    print "And this one was:" + str
´´´

**Comment by nathanalderson** [comment]
Well it seems like `:make build` is doing the same thing as a regular `gradle build`, which is all it is supposed to do.  It sounds like the problem is in your `build.gradle` file, not with this plugin.

**Comment by niccolomineo** [comment]
Ok, thank you.

I now prepended `apply plugin: "groovy"` to the comments in the `build.gradle` file and I can now see more tasks when doing `gradle tasks`. What should then be done in order to run the code?

Thank you

**Comment by nathanalderson** [comment]
I would direct you to the [gradle documentation](
https://docs.gradle.org/current/userguide/userguide.html) for those
questions. This plugin just simplifies calling gradle from vim.

**Comment by niccolomineo** [comment]
Hi, thanks. I believe I fixed my `build.gradle`. Now I have a problem and I don't know whether it is related to this plugin or not. My build fails like this:

```
:compileJava UP-TO-DATE
:compileGroovy UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:exerciseA
Please key in a word: Exception in thread "main" java.lang.NullPointerException: Cannot invoke method readList() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:77)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:45)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:32)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at exerciseA.run(exerciseA.groovy:3)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1085)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:848)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:831)
	at org.codehaus.groovy.runtime.InvokerHelper.runScript(InvokerHelper.java:407)
	at org.codehaus.groovy.runtime.InvokerHelper$runScript.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
	at exerciseA.main(exerciseA.groovy)
:exerciseA FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':exerciseA'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.584 secs
```

**Comment by tfnico** [comment]
@niccolomineo with all respect, this repository is just a Vim plugin. It's not a Groovy help group. You're better off googling these sorts of problems (for example this was the top hit when searching for "System.console java groovy": http://stackoverflow.com/questions/4203646/system-console-returns-null ).

**Comment by niccolomineo** [comment]
Hi, sorry. I thought this time the problem could have been related to the plugin
